# Generated by Django 3.2 on 2022-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='products',
            field=models.ManyToManyField(related_name='product_favorite', through='favorites.FavoriteItem', to='products.Product'),
        ),
    ]
